"use client";
import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, Download, ExternalLink, LayoutDashboard, Printer, QrCode, Refrigerator, Search, Snowflake, Thermometer, RefreshCw, Settings2 } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import QRCode from 'qrcode';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { type Reading, type Unit, UNITS, TIMES, businessDate, slots, currentSlot, temperatureStatus, evaluateTemperature, readingSnapshot, policyText, POLICIES, STATUS_COLORS, temperatureText, timeText, dateText, roundStatus } from '@/lib/temperature';

const SHEET_URL='https://docs.google.com/spreadsheets/d/1pv8M0JS6VMIX__p7I5vv7x4-8OYX6mhBE7XUFx_1TQQ/edit';
const statusClass=(label:string)=>label==='ปกติ'||label==='บันทึกแล้ว'?'good':label==='วิกฤต'?'critical':label==='เฝ้าระวัง'?'warning':label==='ผิดปกติ'||label==='ผิดเกณฑ์'||label==='ขาดบันทึก'?'bad':label==='รอบปัจจุบัน'?'due':'neutral';
function Badge({label}:{label:string}){return <span className={'status '+statusClass(label)}>{label}</span>;}
function QR({unit,base}:{unit:string;base:string}){
 const [image,setImage]=useState('');const [error,setError]=useState(false);
 useEffect(()=>{let valid=true;setError(false);if(base)QRCode.toDataURL(`${base}?unit=${unit}`,{width:300,margin:4,errorCorrectionLevel:'M'}).then(src=>{if(valid)setImage(src);}).catch(()=>{if(valid)setError(true);});return ()=>{valid=false;};},[base,unit]);
 return image?<img src={image} alt={'QR บันทึกตู้ '+unit} width={120} height={120}/>:<span className="qr-placeholder">{error?'สร้าง QR ไม่สำเร็จ':'กำลังสร้าง QR'}</span>;
}
export default function Home(){
 const [mounted,setMounted]=useState(false), [now,setNow]=useState(new Date('2026-09-20T00:00:00Z'));
 const [day,setDay]=useState('2026-09-20'),[view,setView]=useState('dashboard'),[units,setUnits]=useState<Unit[]>(UNITS),[readings,setReadings]=useState<Reading[]>([]);
 const [mode,setMode]=useState<'loading'|'offline'|'live'|'demo'>('loading'),[loadError,setLoadError]=useState(''),[busy,setBusy]=useState(false),[fetchedAt,setFetchedAt]=useState('');
 const [selected,setSelected]=useState('FZ-01'),[locked,setLocked]=useState(false),[invalidQr,setInvalidQr]=useState(false),[base,setBase]=useState('');
 const [temperature,setTemperature]=useState(''),[recorder,setRecorder]=useState(''),[note,setNote]=useState(''),[message,setMessage]=useState(''),[formError,setFormError]=useState(''),[saving,setSaving]=useState(false);
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[chartType,setChartType]=useState('Frozen'),[detail,setDetail]=useState<string|null>(null);
 const pendingId=useRef<string|null>(null),serverOffset=useRef(0),loadSeq=useRef(0);
 const active=currentSlot(now),selectedUnit=units.find(u=>u.id===selected)??UNITS[0];
 const previousSlot=useRef('');
 async function refresh(targetDay:string){
  const seq=++loadSeq.current;setBusy(true);setLoadError('');
  try{const res=await fetch('/api/temperature?day='+targetDay,{cache:'no-store'});const data=await res.json() as {connected?:boolean;ok?:boolean;error?:string;units:Unit[];readings:Reading[];serverNow:string};if(seq!==loadSeq.current)return;
   if(data.connected===false){setMode('offline');setReadings([]);return;}
   if(!res.ok||!data.ok)throw new Error(data.error||'โหลดข้อมูลไม่สำเร็จ');
   setUnits(data.units);setReadings(data.readings);setMode('live');setFetchedAt(new Date().toISOString());
   serverOffset.current=Date.parse(data.serverNow)-Date.now();setNow(new Date(Date.now()+serverOffset.current));
  }catch(e){if(seq===loadSeq.current){setLoadError((e as Error).message);setMode('offline');setReadings([]);}}
  finally{if(seq===loadSeq.current)setBusy(false);}
 }
 useEffect(()=>{setMounted(true);const time=new Date();setNow(time);setDay(businessDate(time));setBase(window.location.origin+window.location.pathname);
  const id=new URLSearchParams(window.location.search).get('unit');if(id){setView('record');if(UNITS.some(u=>u.id===id)){setSelected(id);setLocked(true);}else setInvalidQr(true);}
  setRecorder(localStorage.getItem('villa-temperature-recorder')||'');void refresh(businessDate(time));
  const timer=setInterval(()=>setNow(new Date(Date.now()+serverOffset.current)),15000);return()=>clearInterval(timer);
 },[]);
 useEffect(()=>{if(!mounted)return;const key=active.day+active.slot.time;if(previousSlot.current&&previousSlot.current!==key){setMessage('');setFormError('เปลี่ยนเป็นรอบ '+active.slot.time+' แล้ว กรุณาตรวจค่าอีกครั้งก่อนบันทึก');setTemperature('');pendingId.current=null;}previousSlot.current=key;},[active.day,active.slot.time,mounted]);
 useEffect(()=>{if(mode!=='live')return;const timer=setInterval(()=>void refresh(day),60000);return()=>clearInterval(timer);},[mode,day]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,opts:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  void Promise.resolve(context.registerTool({name:'start_temperature_recording',title:'เปิดฟอร์มบันทึกอุณหภูมิ',description:'เปิดฟอร์มตามรหัสตู้ ยังไม่ส่งข้อมูล',inputSchema:{type:'object',properties:{unit:{type:'string'}},required:['unit'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const id=(input as {unit?:string})?.unit;if(!id||!UNITS.some(u=>u.id===id))throw new Error('ไม่พบรหัสตู้');if(locked&&id!==selected)throw new Error('QR นี้ใช้สำหรับตู้ '+selected);setSelected(id);setView('record');setMessage('');return {status:'form_opened',unit:id};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();
 },[locked,selected]);
 const daily=useMemo(()=>readings.filter(r=>r.businessDate===day),[readings,day]);
 const latest=useMemo(()=>{const map=new Map<string,Reading>();for(const r of daily){if(!map.has(r.unit)||map.get(r.unit)!.recordedAt<r.recordedAt)map.set(r.unit,r);}return map;},[daily]);
 const hasData=mode==='live'||mode==='demo';
 const dueSlots=slots(day).filter(s=>Date.parse(s.at)<=now.getTime());
 const unique=new Set(daily.map(r=>r.unit+'|'+r.slot));
 const missing=units.reduce((n,u)=>n+TIMES.filter(t=>roundStatus(day,t,u.id,daily,now).label==='ขาดบันทึก').length,0);
 const abnormal=units.filter(u=>['ผิดปกติ','ผิดเกณฑ์','วิกฤต'].includes(temperatureStatus(u,latest.get(u.id))));
 const warning=units.filter(u=>temperatureStatus(u,latest.get(u.id))==='เฝ้าระวัง').length;
 const critical=units.filter(u=>temperatureStatus(u,latest.get(u.id))==='วิกฤต').length;
 const normals=units.filter(u=>temperatureStatus(u,latest.get(u.id))==='ปกติ').length;
 const filtered=units.filter(u=>(filter==='all'||u.type===filter)&&`${u.id} ${u.zone}`.toLowerCase().includes(query.toLowerCase()));
 const chart=units.filter(u=>u.type===chartType).map(u=>({id:u.id,value:latest.get(u.id)?.temperature??null,status:temperatureStatus(u,latest.get(u.id))}));
 function chooseDay(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return;setDay(value);if(mode!=='demo')void refresh(value);}
 function openRecord(id:string){if(mode==='live'&&day!==active.day){setDay(active.day);void refresh(active.day);}setSelected(id);setView('record');setMessage('');setFormError('');setTemperature('');pendingId.current=null;setDetail(null);}
 function demo(){++loadSeq.current;setBusy(false);setMode('demo');setLoadError('');setDay(active.day);const demoUnits=UNITS;setUnits(demoUnits);
  const data:Reading[]=[];for(const s of slots(active.day).filter(s=>Date.parse(s.at)<now.getTime()-1800000)){demoUnits.forEach((u,i)=>{if((i+s.time.charCodeAt(0))%9===0)return;const value=u.type==='Frozen'?(i===7?-10:i===3?-14.5:i===4?-18:-21-(i%4)*.4):(i===27?6.4:2.2+(i%4)*.5);data.push({id:`demo-${s.time}-${u.id}`,businessDate:active.day,slot:s.time,scheduledAt:s.at,recordedAt:new Date(Date.parse(s.at)+((i%18)+1)*60000).toISOString(),unit:u.id,type:u.type,temperature:value,recorder:'พนักงานตัวอย่าง '+(i%3+1),note:'ข้อมูลสาธิต',...readingSnapshot(u,value)});});}setReadings(data);
 }
 async function submit(event:React.FormEvent){event.preventDefault();setMessage('');setFormError('');if(saving||mode==='offline'||mode==='loading')return;
  const value=Number(temperature);if(!temperature.trim()||!Number.isFinite(value)||value< -80||value>80||!recorder.trim()){setFormError('กรอกอุณหภูมิ -80 ถึง 80°C และชื่อผู้บันทึก');return;}
  const actual=new Date(Date.now()+serverOffset.current),current=currentSlot(actual);if(current.day!==active.day||current.slot.time!==active.slot.time){setNow(actual);setFormError('เปลี่ยนรอบแล้ว กรุณาตรวจรอบปัจจุบันก่อนบันทึก');return;}
  const id=pendingId.current||Array.from(crypto.getRandomValues(new Uint8Array(16)),byte=>byte.toString(16).padStart(2,'0')).join('');pendingId.current=id;const payload={id,businessDate:current.day,slot:current.slot.time,unit:selected,temperature:value,recorder:recorder.trim(),note:note.trim()};setSaving(true);
  try{let reading:Reading;
   if(mode==='demo'){reading={...payload,type:selectedUnit.type,scheduledAt:current.slot.at,recordedAt:actual.toISOString(),...readingSnapshot(selectedUnit,value)};}
   else{const res=await fetch('/api/temperature',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json() as {ok?:boolean;error?:string;reading:Reading};if(!res.ok||!data.ok)throw new Error(data.error||'ยังไม่ยืนยันการบันทึก');reading=data.reading;}
   setReadings(rs=>[...rs.filter(r=>r.id!==reading.id),reading]);setDay(current.day);pendingId.current=null;localStorage.setItem('villa-temperature-recorder',recorder.trim());setTemperature('');setNote('');setMessage(mode==='demo'?'ทดลองบันทึกแล้ว — ข้อมูลนี้อยู่เฉพาะหน้าทดลอง':'บันทึกเข้า Google Sheets แล้ว เวลา '+timeText(reading.recordedAt)+' น.');
  }catch(e){setFormError((e as Error).message);}finally{setSaving(false);}
 }
 function exportCsv(){const data=[['วันงาน','รอบ','เวลารอบ','เวลาบันทึกจริง','ตู้','ประเภท','อุณหภูมิ','ผู้บันทึก','หมายเหตุ','ประเภทสินค้า ณ เวลาบันทึก','สถานะ ณ เวลาบันทึก'],...daily.map(r=>[r.businessDate,r.slot,r.scheduledAt,r.recordedAt,r.unit,r.type,r.temperature,r.recorder,r.note,r.category||'',temperatureStatus(r,r)])];const safe=(v:unknown)=>{let s=String(v);if(typeof v==='string'&&/^[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const blob=new Blob(['\ufeff'+data.map(row=>row.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${mode==='demo'?'DEMO_':''}Temperature_${day}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 const detailUnit=units.find(u=>u.id===detail),detailRows=daily.filter(r=>r.unit===detail).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt));
 return <main>
  <header className="site-header no-print"><div className="header-inner"><div className="brand"><span className="brand-mark"><Snowflake/></span><div><p className="brand-name">VILLA MARKET</p><h1>Cold Chain Monitor</h1></div></div><div className="header-state"><Clock3 size={17}/><span>{mounted?timeText(now.toISOString()):'—'} น. · เวลาไทย</span></div></div></header>
  <div className="workspace">
   <div className="page-heading no-print"><div><p className="eyebrow">สุขุมวิท 33 / TEMPERATURE RECORD</p><h2>ตรวจอุณหภูมิให้ครบ ทุก 2 ชั่วโมง</h2><p className="muted">37 ตู้ · 12 รอบ · 07:00 ถึง 05:00 ของเช้าวันถัดไป</p></div><a href={SHEET_URL} target="_blank" rel="noreferrer" className="sheet-link">เปิด Google Sheets <ExternalLink size={15}/></a></div>
   <div className={'connection no-print '+(mode==='live'?'connected':'')} role="status"><span>{mode==='loading'?'กำลังตรวจการเชื่อมต่อ…':mode==='demo'?'โหมดทดลอง • อุณหภูมิและรายชื่อเป็นข้อมูลตัวอย่าง · ใช้เกณฑ์ที่กำหนด การทดลองจะหายเมื่อปิดหน้า':mode==='live'?`เชื่อมต่อ Google Sheets · ดึงข้อมูล ${fetchedAt?timeText(fetchedAt):'—'} น.`:'ยังไม่ได้เชื่อมบันทึกเข้า Google Sheets · ทะเบียนตู้และรอบตรวจเตรียมไว้แล้ว'}</span>{mode!=='live'&&mode!=='demo'&&<Button variant="outline" onClick={demo}>ทดลองใช้งาน</Button>}{mode==='demo'&&<Button variant="outline" onClick={()=>{setReadings([]);setUnits(UNITS);void refresh(day);}}>ออกจากโหมดทดลอง</Button>}</div>
   {loadError&&<p className="error no-print" role="alert">{loadError}</p>}
   <Tabs value={view} onValueChange={value=>{setView(value);if(value==='record'&&mode==='live'&&day!==active.day){setDay(active.day);void refresh(active.day);}}}>
    <TabsList className="main-tabs no-print"><TabsTrigger value="dashboard"><LayoutDashboard size={17}/>ภาพรวม</TabsTrigger><TabsTrigger value="record"><Thermometer size={17}/>บันทึก</TabsTrigger><TabsTrigger value="units"><QrCode size={17}/>รายตู้ & QR</TabsTrigger><TabsTrigger value="setup"><Settings2 size={17}/>ตั้งค่า</TabsTrigger></TabsList>
    <TabsContent value="dashboard" className="space-y-5">
     <div className="toolbar"><div><Label htmlFor="business-day">วันงาน</Label><Input id="business-day" type="date" value={day} onChange={e=>chooseDay(e.target.value)} max={businessDate(now)}/></div><p className="muted">{dateText(day)}<br/><small>01:00 / 03:00 / 05:00 อยู่ในวันงานนี้</small></p><Button variant="outline" disabled={busy||mode==='demo'} onClick={()=>void refresh(day)}><RefreshCw size={16} className={busy?'animate-spin':''}/>อัปเดต</Button></div>
     <section className="metrics"><div className="metric-card"><span className="metric-icon blue"><Refrigerator/></span><div><p>ตู้ทั้งหมด</p><strong>{units.length} <small>ตู้</small></strong><small>Frozen 24 · Chill 13</small></div></div><div className="metric-card"><span className="metric-icon green"><CheckCircle2/></span><div><p>ค่าล่าสุดปกติ</p><strong>{normals} <small>ตู้</small></strong><small>{units.length-latest.size} ตู้ยังไม่มีค่าของวันงานนี้</small></div></div><div className="metric-card"><span className="metric-icon red"><AlertTriangle/></span><div><p>ผิดปกติ / วิกฤต</p><strong>{abnormal.length} <small>ตู้</small></strong><small>วิกฤต {critical} · เฝ้าระวัง {warning}</small></div></div><div className="metric-card"><span className="metric-icon cyan"><Clock3/></span><div><p>บันทึกแล้ว / เป้าหมาย</p><strong>{hasData?unique.size:'—'}<small> / 444</small></strong><small>{hasData?`ถึงรอบแล้ว ${dueSlots.length*units.length} · ขาด ${missing}`:'รอการเชื่อมต่อข้อมูล'}</small></div></div></section><p className="muted">{units.filter(u=>!u.policy).length} ตู้รอกำหนดประเภทสินค้า · สถานะอุณหภูมิใช้เกณฑ์ ณ เวลาที่บันทึก</p>
     <section className="panel"><div className="panel-heading"><div><h3>ความครบถ้วนแต่ละรอบ</h3><p>นับตู้ไม่ซ้ำ · บันทึกซ้ำยังนับเป็น 1 ตู้ในรอบนั้น</p></div><span className="timezone">Asia/Bangkok</span></div><div className="round-grid">{slots(day).map(s=>{const count=new Set(daily.filter(r=>r.slot===s.time).map(r=>r.unit)).size;const future=Date.parse(s.at)>now.getTime();const closed=Date.parse(s.at)+7200000<=now.getTime();return <div key={s.time} className={'round '+(!hasData||future?'future':count===units.length?'complete':closed?'missing':'current')}><div><strong>{s.time}</strong><small>{s.nextDay?'วันถัดไป':'วันนี้'}</small></div><b>{!hasData||future?'—':`${count}/${units.length}`}</b><span>{!hasData?'รอข้อมูล':future?'ยังไม่ถึงรอบ':count===units.length?'ครบแล้ว':closed?'ขาด '+(units.length-count)+' ตู้':'รอบปัจจุบัน'}</span></div>;})}</div><p className="round-note">“ขาดบันทึก” หมายถึงจบรอบ 2 ชั่วโมงแล้วยังไม่มีข้อมูล • ยังไม่ตัดสินตรงเวลา/สายจนกว่าจะกำหนดช่วงผ่อนผัน</p></section>
     <section className="panel"><div className="panel-heading"><div><h3>เปรียบเทียบอุณหภูมิล่าสุดรายตู้</h3><p>ค่าที่พนักงานบันทึก ไม่ใช่ข้อมูลจากเซนเซอร์แบบสด</p></div><Select value={chartType} onValueChange={setChartType}><SelectTrigger className="w-[140px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Frozen">Frozen</SelectItem><SelectItem value="Chill">Chill</SelectItem></SelectContent></Select></div><div className="temperature-legend">{['ปกติ','เฝ้าระวัง','ผิดปกติ','วิกฤต','รอกำหนดประเภทสินค้า'].map(label=><Badge key={label} label={label}/>)}</div><div className="chart-scroll"><div className="bar-chart" style={{minWidth:chartType==='Frozen'?750:500}}>{mounted&&<ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:25,left:4,right:15,bottom:10}}><CartesianGrid strokeDasharray="3 4" vertical={false}/><XAxis dataKey="id" tick={{fontSize:12}} angle={-45} textAnchor="end" height={60} interval={0}/><YAxis unit="°C" width={60}/><ReferenceLine y={0} stroke="#8da0b7"/><Tooltip formatter={(v)=>[`${v}°C`,'อุณหภูมิ']}/><Bar dataKey="value" maxBarSize={28} radius={[4,4,0,0]}>{chart.map(c=><Cell key={c.id} fill={STATUS_COLORS[c.status]||'#94a3b8'}/>)}</Bar></BarChart></ResponsiveContainer>}</div></div>{!daily.length&&<p className="empty-inline">ยังไม่มีข้อมูลบันทึกสำหรับวันงานนี้</p>}</section>
     <section className="panel"><div className="panel-heading"><div><h3>ตรวจสอบรายตู้</h3><p>คลิกรหัสตู้เพื่อดูประวัติและรอบตรวจทั้ง 12 รอบ</p></div><Button variant="outline" onClick={exportCsv} disabled={!daily.length}><Download size={16}/>รายงาน CSV</Button></div><Filters filter={filter} setFilter={setFilter} query={query} setQuery={setQuery}/><Table><TableHeader><TableRow><TableHead>รหัสตู้</TableHead><TableHead>ประเภท</TableHead><TableHead>อุณหภูมิล่าสุด</TableHead><TableHead>ผู้บันทึก / เวลาไทย</TableHead><TableHead>อุณหภูมิ</TableHead><TableHead>รอบที่บันทึก</TableHead></TableRow></TableHeader><TableBody>{filtered.map(u=>{const r=latest.get(u.id);return <TableRow key={u.id}><TableCell><button className="unit-id" onClick={()=>setDetail(u.id)}>{u.id}</button></TableCell><TableCell>{u.type}<small className="block muted">{r?(r.category||'ยังไม่ระบุสินค้า ณ เวลาบันทึก'):(u.category||'รอกำหนดสินค้า')}</small></TableCell><TableCell className="temperature-value">{r?`${temperatureText(r.temperature)}°C`:'—'}</TableCell><TableCell>{r?<>{r.recorder}<small className="block muted">{timeText(r.recordedAt)} น. · {['01:00','03:00','05:00'].includes(r.slot)?'วันถัดไป':''}</small></>:'ยังไม่มีบันทึก'}</TableCell><TableCell><Badge label={temperatureStatus(u,r)}/></TableCell><TableCell>{new Set(daily.filter(r=>r.unit===u.id).map(r=>r.slot)).size} / 12</TableCell></TableRow>;})}</TableBody></Table>{!filtered.length&&<p className="empty-inline">ไม่พบตู้ที่ค้นหา</p>}</section>
    </TabsContent>
    <TabsContent value="record"><div className="record-layout"><form className="panel record-form" onSubmit={submit}><div className="form-heading"><span className="brand-mark"><Thermometer/></span><div><h3>บันทึกอุณหภูมิ</h3><p className="muted">รอบ {active.slot.time} น. · วันงาน {dateText(active.day)}</p></div></div>{invalidQr?<p className="error">ไม่พบรหัสตู้ใน QR นี้ กรุณาเปิดจาก QR ของตู้ที่ลงทะเบียน</p>:<><Label htmlFor="unit">หมายเลขตู้ {locked?'· ระบุจาก QR แล้ว':''}</Label><Select value={selected} disabled={locked} onValueChange={id=>openRecord(id)}><SelectTrigger id="unit" className="w-full h-12"><SelectValue/></SelectTrigger><SelectContent>{units.map(u=><SelectItem key={u.id} value={u.id}>{u.id} · {u.type}</SelectItem>)}</SelectContent></Select><div className="unit-info"><div><small>ประเภทตู้ / สินค้า</small><b>{selectedUnit.type}</b><p>{selectedUnit.category||'รอกำหนดประเภทสินค้า'}</p></div><div><small>เกณฑ์ที่กำหนด</small><b>{policyText(selectedUnit.policy)}</b></div></div><Label htmlFor="temperature">อุณหภูมิที่อ่านได้ (°C)</Label><Input id="temperature" className="temperature-input" type="number" min={-80} max={80} step="any" required value={temperature} onChange={e=>{setTemperature(e.target.value);pendingId.current=null;}} placeholder={selectedUnit.type==='Frozen'?'-21.0':'2.0'}/>{temperature.trim()&&Number.isFinite(Number(temperature))&&<div aria-live="polite"><Badge label={evaluateTemperature(selectedUnit.policy,Number(temperature))}/></div>}<Label htmlFor="recorder">ชื่อผู้บันทึก</Label><Input id="recorder" value={recorder} required maxLength={100} onChange={e=>{setRecorder(e.target.value);pendingId.current=null;}} placeholder="ชื่อ-นามสกุล"/><p className="muted small-note">ชื่อที่กรอกใช้ระบุผู้บันทึก ยังไม่ได้ยืนยันด้วยบัญชีพนักงาน</p><Label htmlFor="note">หมายเหตุ / การแก้ไข (ถ้ามี)</Label><Input id="note" value={note} maxLength={500} onChange={e=>{setNote(e.target.value);pendingId.current=null;}} placeholder="เช่น ตรวจย้ำหลังปิดประตูตู้"/>{message&&<p className="success" role="status">{message}</p>}{formError&&<p className="error" role="alert">{formError}</p>}<Button type="submit" className="submit-button" disabled={saving||mode==='loading'||mode==='offline'}>{saving?'กำลังบันทึก…':mode==='demo'?'ทดลองบันทึก':mode==='offline'?'รอเชื่อม Google Sheets':'บันทึกอุณหภูมิ'}</Button><p className="muted small-note">ระบบใส่วันเวลาอัตโนมัติ การวัดซ้ำเก็บเป็นรายการใหม่โดยไม่ลบประวัติ</p></>}</form><aside className="panel"><h3>รอบตรวจของ {selected}</h3><p className="muted">วันงาน {dateText(active.day)}</p><div className="record-rounds">{TIMES.map(t=>{const s=roundStatus(active.day,t,selected,readings,now);return <div key={t}><strong>{t}</strong><Badge label={hasData?s.label:'รอข้อมูล'}/>{s.reading&&<small>{s.reading.temperature}°C · {timeText(s.reading.recordedAt)} น.</small>}</div>;})}</div></aside></div></TabsContent>
    <TabsContent value="units"><div className="panel no-print"><div className="panel-heading"><div><h3>QR ประจำตู้ 37 ตู้</h3><p>สแกนเพื่อเปิดฟอร์มพร้อมรหัสตู้ · ใช้บัญชีและรหัสผ่านของทีมเพื่อเปิดเว็บ</p></div><Button variant="outline" onClick={()=>window.print()} disabled={!base}><Printer size={16}/>พิมพ์ QR ที่แสดง</Button></div><Filters filter={filter} setFilter={setFilter} query={query} setQuery={setQuery}/></div><div className="unit-grid">{filtered.map(u=><article key={u.id} className="unit-card"><div className="qr-card-heading"><div><p className="eyebrow">{u.type}</p><h3>{u.id}</h3><p>{u.zone||'ยังไม่ระบุตำแหน่ง'}</p></div><Snowflake className="text-blue-600"/></div><div className="qr-row"><QR unit={u.id} base={base}/><div><strong>{latest.get(u.id)?`${temperatureText(latest.get(u.id)!.temperature)}°C`:'—'}</strong><Badge label={temperatureStatus(u,latest.get(u.id))}/></div></div><p className="qr-instruction">สแกนเพื่อบันทึกอุณหภูมิ</p><div className="card-actions no-print"><Button variant="outline" onClick={()=>setDetail(u.id)}>ประวัติ</Button><Button onClick={()=>{if(locked&&selected!==u.id){window.location.href=base+'?unit='+u.id;}else openRecord(u.id);}}>บันทึก</Button></div></article>)}</div></TabsContent>
    <TabsContent value="setup"><section className="panel setup policy-panel"><h3>เกณฑ์อุณหภูมิที่กำหนด</h3><p>ตามเกณฑ์ของสาขา · Chill ทั้ง 13 ตู้รอกำหนดประเภทสินค้า</p><Table><TableHeader><TableRow><TableHead>ประเภทสินค้า</TableHead><TableHead>ปกติ</TableHead><TableHead>เฝ้าระวัง</TableHead><TableHead>ผิดปกติ</TableHead><TableHead>วิกฤต</TableHead></TableRow></TableHeader><TableBody>{POLICIES.map(p=><TableRow key={p.id}><TableCell>{p.label}</TableCell><TableCell>≤ {p.max}°C</TableCell><TableCell>{p.warningMax===null?'—':`> ${p.max} ถึง ≤ ${p.warningMax}°C`}</TableCell><TableCell>{`> ${p.warningMax??p.max}`}{p.criticalMin!==null?` ถึง ${p.criticalInclusive?'<':'≤'} ${p.criticalMin}`:''}°C</TableCell><TableCell>{p.criticalMin===null?'ยังไม่กำหนด':`${p.criticalInclusive?'≥':'>'} ${p.criticalMin}°C`}</TableCell></TableRow>)}</TableBody></Table><p className="muted">ตู้ที่ยังไม่กำหนดสินค้าบันทึกค่าได้ แต่ยังไม่ตัดสินว่าปกติหรือผิดปกติ</p></section><section className="panel setup"><h3>เชื่อมต่อ TemperatureRecord</h3><p>เตรียมไว้แล้ว 3 ชีท: ทะเบียนตู้ 37 ตู้, บันทึกอุณหภูมิ และรอบตรวจ 12 รอบ</p><a className="sheet-link" href={SHEET_URL} target="_blank" rel="noreferrer">เปิดไฟล์ TemperatureRecord <ExternalLink size={16}/></a><ol><li>ใส่ตำแหน่งใน “ทะเบียนตู้” คอลัมน์ C และเลือกประเภทสินค้าของ Chill ในคอลัมน์ F เมื่อทราบข้อมูล เกณฑ์ปกติใน E จะคำนวณให้อัตโนมัติ</li><li>เปิดเมนู ส่วนขยาย → Apps Script ใน Google Sheets แล้ววางโค้ดจากปุ่มด้านล่าง</li><li>ตั้ง Script Property ชื่อ <code>TEMPERATURE_API_KEY</code> เป็นรหัสลับของระบบที่เดายาก</li><li>เผยแพร่ Apps Script เป็น Web app ที่ทำงานในนามเจ้าของ และให้เซิร์ฟเวอร์เข้าถึงได้ โค้ดจะตรวจรหัสลับทุกคำขอ</li><li>ตั้งค่า <code>GAS_ENDPOINT</code> และรหัสลับ <code>GAS_API_KEY</code> ใน Cloudflare → Settings → Variables and Secrets จากนั้นทดสอบการบันทึกเข้า Sheets ก่อนให้พนักงานใช้</li></ol><a className="download-code" href="/Code.gs" download>ดาวน์โหลด Code.gs</a><p className="muted">การเปิดเว็บและ QR ใช้ชื่อผู้ใช้และรหัสผ่านของทีมที่ผู้ดูแลกำหนดใน Cloudflare</p><p className="muted">การตัดสินตรงเวลา/สายยังรอระบุช่วงผ่อนผัน ปัจจุบันแสดงเวลาบันทึกจริงและจำนวนรอบที่ขาด</p><a className="sheet-link" href="https://developers.google.com/apps-script/guides/web" target="_blank" rel="noreferrer">คู่มือเผยแพร่ Web app ของ Google <ExternalLink size={15}/></a></section></TabsContent>
   </Tabs>
  </div>
  <Sheet open={!!detail} onOpenChange={open=>{if(!open)setDetail(null);}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{detailUnit?.id} · {detailUnit?.type}</SheetTitle><SheetDescription>ประวัติวันงาน {dateText(day)}</SheetDescription></SheetHeader>{detailUnit&&<div className="detail-body"><Button onClick={()=>openRecord(detailUnit.id)}>บันทึกอุณหภูมิรอบปัจจุบัน</Button><div className="record-rounds">{TIMES.map(t=>{const s=roundStatus(day,t,detailUnit.id,daily,now);return <div key={t}><strong>{t}</strong><Badge label={hasData?s.label:'รอข้อมูล'}/><small>{s.reading?`${s.reading.temperature}°C · ${s.count} ครั้ง`:'—'}</small></div>;})}</div><h3>ประวัติการบันทึกทั้งหมด</h3>{!detailRows.length&&<p className="muted">ยังไม่มีบันทึกในวันงานนี้</p>}{detailRows.map(r=><div className="history" key={r.id}><div><b>{temperatureText(r.temperature)}°C</b><Badge label={temperatureStatus(r,r)}/></div><p>รอบ {r.slot} · {r.recorder}</p><p className="muted">{r.category||'ยังไม่ระบุสินค้า ณ เวลาบันทึก'}</p><p className="muted">{new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'short',timeStyle:'medium'}).format(new Date(r.recordedAt))}</p><small>หลังเวลารอบ {Math.floor((Date.parse(r.recordedAt)-Date.parse(r.scheduledAt))/60000)} นาที{r.note?' · '+r.note:''}</small></div>)}</div>}</SheetContent></Sheet>
 </main>;
}
function Filters({filter,setFilter,query,setQuery}:{filter:string;setFilter:(v:string)=>void;query:string;setQuery:(v:string)=>void}){return <div className="filters"><div className="search"><Search size={16}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหารหัสตู้ / ตำแหน่ง" aria-label="ค้นหาตู้"/></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-[150px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">ทุกประเภท</SelectItem><SelectItem value="Frozen">Frozen 24 ตู้</SelectItem><SelectItem value="Chill">Chill 13 ตู้</SelectItem></SelectContent></Select></div>;}
